### ISSUE TITLE
Problem with print_qiime_config.py

### ISSUE THREAD

**Issue by MikeGJohnson** [alk224/akutils_ubuntu_installer#1]
Hey Andy!

This is probably just because I don't understand enough to know where I'm screwing up, but...

I am trying to run your tutorial so that I can be prepared for data (hopefully getting it on Monday). I can't get past the installation though. Everything seems to work fine, and I get to the part that says "Installations Complete (hopefully)" but the test that it says to do just gets me "command not found". When I scroll up it looks like there were some errors installing vsearch and bamtools:
Installing vsearch.

cp: cannot stat '/home/mike//vsearch/bin/vsearch': No such file or directory
Installing bamtools.

cp: cannot stat '/home/mike//bamtools/bin/bamtools': No such file or directory

and then a bit latter here:

Executing QIIME deploy script.

chown: cannot access '/home/mike//qiime_1.9.1/': No such file or directory
analyze_primers.py not where expected. Python library not corrected.

/bin/bash: /home/mike//qiime_1.9.1/activate.sh: No such file or directory
/home/mike/akutils_ubuntu_installer/akutils_ubuntu_installation.sh: line 430: /home/mike//qiime_1.9.1/activate.sh: No such file or directory
/home/mike/akutils_ubuntu_installer/akutils_ubuntu_installation.sh: line 431: print_qiime_config.py: command not found

Any ideas?

Thanks!
Mike

**Comment by alk224** [comment]
Hi Mike,

Sounds like you still need to source your .bashrc file because the commands
are not yet in your system path.

Type this and try again:

source ~/.bashrc

## 

Andrew Krohn
PhD Candidate, NAU Biological Sciences
Research Technician, EnGGen

**Comment by MikeGJohnson** [comment]
That didn't seem to work, for some reason it wasn't installing bamtools,
vsearch, or qiime. I mannually installed them and I think it is working ow.

Thanks!
Mike

On Fri, May 6, 2016 at 12:22 PM, alk224 notifications@github.com wrote:

> Hi Mike,
> 
> Sounds like you still need to source your .bashrc file because the commands
> are not yet in your system path.
> 
> Type this and try again:
> 
> source ~/.bashrc
> 
> ## 
> 
> Andrew Krohn
> PhD Candidate, NAU Biological Sciences
> Research Technician, EnGGen
> 
> On Fri, May 6, 2016 at 12:08 PM, MikeGJohnson notifications@github.com
> wrote:
> 
> > Hey Andy!
> > 
> > This is probably just because I don't understand enough to know where I'm
> > screwing up, but...
> > 
> > I am trying to run your tutorial so that I can be prepared for data
> > (hopefully getting it on Monday). I can't get past the installation
> > though.
> > Everything seems to work fine, and I get to the part that says
> > "Installations Complete (hopefully)" but the test that it says to do just
> > gets me "command not found". When I scroll up it looks like there were
> > some
> > errors installing vsearch and bamtools:
> > Installing vsearch.
> > 
> > cp: cannot stat '/home/mike//vsearch/bin/vsearch': No such file or
> > directory
> > Installing bamtools.
> > 
> > cp: cannot stat '/home/mike//bamtools/bin/bamtools': No such file or
> > directory
> > 
> > and then a bit latter here:
> > 
> > Executing QIIME deploy script.
> > 
> > chown: cannot access '/home/mike//qiime_1.9.1/': No such file or
> > directory
> > analyze_primers.py not where expected. Python library not corrected.
> > 
> > /bin/bash: /home/mike//qiime_1.9.1/activate.sh: No such file or directory
> > /home/mike/akutils_ubuntu_installer/akutils_ubuntu_installation.sh: line
> > 430: /home/mike//qiime_1.9.1/activate.sh: No such file or directory
> > /home/mike/akutils_ubuntu_installer/akutils_ubuntu_installation.sh: line
> > 431: print_qiime_config.py: command not found
> > 
> > Any ideas?
> > 
> > Thanks!
> > Mike
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/alk224/akutils_ubuntu_installer/issues/1
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217535739

## 

Mike Johnson, MSF
PhD Student, Garbelotto Lab
University of California at Berkeley
Depart of Environmental Science, Policy, and Management

**Comment by alk224** [comment]
Sometimes the path variable isn't successfully changed during the install
process. Logging out and logging in and rerunning the installer up to 3
times can solve issues like this. Since the install functions are all
behind conditional statements, it shouldn't rerun any commands except
qiime-deploy, so the really painful steps like the R updates won't happen
over again.

## 

Andrew Krohn
PhD Candidate, NAU Biological Sciences
Research Technician, EnGGen

**Comment by alk224** [comment]
You probably need to rerun the installer anyway because the analyze_primers issue is important for the format_database step (if following the full tutorial). Again, just log out and log back in and rerun the installer a couple of times.

**Comment by MikeGJohnson** [comment]
Yeah, it looks like I am missing some things. Do you mean to rerun every
step of the installation or just the last one?

Mike

On Fri, May 6, 2016 at 3:00 PM, alk224 notifications@github.com wrote:

> You probably need to rerun the installer anyway because the
> analyze_primers issue is important for the format_database step (if
> following the full tutorial). Again, just log out and log back in and rerun
> the installer a couple of times.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217570759

## 

Mike Johnson, MSF
PhD Student, Garbelotto Lab
University of California at Berkeley
Depart of Environmental Science, Policy, and Management

**Comment by alk224** [comment]
Just issue the same command you did the first time:

sudo bash akutils_ubuntu_installer/akutils_ubuntu_installation.sh install

It should skip over most parts (the ones already completed).

**Comment by MikeGJohnson** [comment]
Gotcha...I am working from a full ubuntu download, not a VM...what do I log
in and out of? The whole Ubuntu OS?

On Fri, May 6, 2016 at 3:42 PM, alk224 notifications@github.com wrote:

> Just issue the same command you did the first time:
> 
> sudo bash akutils_ubuntu_installer/akutils_ubuntu_installation.sh install
> 
> It should skip over most parts (the ones already completed).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217580944

## 

Mike Johnson, MSF
PhD Student, Garbelotto Lab
University of California at Berkeley
Depart of Environmental Science, Policy, and Management

**Comment by alk224** [comment]
Any time you start a fresh terminal instance, it should source your .bashrc file. Type "exit" to close the terminal, and then open a new one (ctrl-alt-t).

**Comment by alk224** [comment]
It is possible that some programs won't fully work until your log in and out of your user account or reboot, but simply closing the terminal and opening a new one should suffice.

**Comment by MikeGJohnson** [comment]
Great thanks! Give Bo and Derek high-fives for me if you see them tonight!

Mike

On Fri, May 6, 2016 at 3:46 PM, alk224 notifications@github.com wrote:

> Any time you start a fresh terminal instance, it should source your
> .bashrc file. Type "exit" to close the terminal, and then open a new one
> (ctrl-alt-t).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217581499

## 

Mike Johnson, MSF
PhD Student, Garbelotto Lab
University of California at Berkeley
Depart of Environmental Science, Policy, and Management

**Comment by alk224** [comment]
Will do. Saw Dereks defense this morning, but missed Bo's. Will meet him at the watering hole instead.

**Comment by MikeGJohnson** [comment]
Nice! Wish we could be there!

On Fri, May 6, 2016 at 4:00 PM, alk224 notifications@github.com wrote:

> Will do. Saw Dereks defense this morning, but missed Bo's. Will meet him
> at the watering hole instead.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217583414

## 

Mike Johnson, MSF
PhD Student, Garbelotto Lab
University of California at Berkeley
Depart of Environmental Science, Policy, and Management

**Comment by MikeGJohnson** [comment]
Well, I've re-installed a number of times and still hitting a dead end here:

analyze_primers.py not where expected. Python library not corrected.

/bin/bash: /home/mike//qiime_1.9.1/activate.sh: No such file or directory
/home/mike/akutils_ubuntu_installer/akutils_ubuntu_installation.sh: line
430: /home/mike//qiime_1.9.1/activate.sh: No such file or directory
/home/mike/akutils_ubuntu_installer/akutils_ubuntu_installation.sh: line
431: print_qiime_config.py: command not found

It was giving this error riight before those: chown: cannot access
'/home/mike//qiime_1.9.1/': No such file or directory    ...but I added a
directory with that name and the error went away..still getting the rest
though.

Any ideas? No rush :-)
Mike

On Fri, May 6, 2016 at 4:03 PM, Michael G Johnson <mike.johnson@berkeley.edu

> wrote:
> 
> Nice! Wish we could be there!
> 
> On Fri, May 6, 2016 at 4:00 PM, alk224 notifications@github.com wrote:
> 
> > Will do. Saw Dereks defense this morning, but missed Bo's. Will meet him
> > at the watering hole instead.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217583414
> 
> ## 
> 
> Mike Johnson, MSF
> PhD Student, Garbelotto Lab
> University of California at Berkeley
> Depart of Environmental Science, Policy, and Management

## 

Mike Johnson, MSF
PhD Student, Garbelotto Lab
University of California at Berkeley
Depart of Environmental Science, Policy, and Management

**Comment by alk224** [comment]
Try a reboot and rerun the installer and let me know if its any different.

## 

Andrew Krohn
PhD Candidate, NAU Biological Sciences
Research Technician, EnGGen

**Comment by MikeGJohnson** [comment]
Same problem, it happens right after "Executing QIIME deploy script."

On Fri, May 6, 2016 at 4:36 PM, alk224 notifications@github.com wrote:

> Try a reboot and rerun the installer and let me know if its any different.
> 
> ## 
> 
> Andrew Krohn
> PhD Candidate, NAU Biological Sciences
> Research Technician, EnGGen
> 
> On Fri, May 6, 2016 at 4:32 PM, MikeGJohnson notifications@github.com
> wrote:
> 
> > Well, I've re-installed a number of times and still hitting a dead end
> > here:
> > 
> > analyze_primers.py not where expected. Python library not corrected.
> > 
> > /bin/bash: /home/mike//qiime_1.9.1/activate.sh: No such file or directory
> > /home/mike/akutils_ubuntu_installer/akutils_ubuntu_installation.sh: line
> > 430: /home/mike//qiime_1.9.1/activate.sh: No such file or directory
> > /home/mike/akutils_ubuntu_installer/akutils_ubuntu_installation.sh: line
> > 431: print_qiime_config.py: command not found
> > 
> > It was giving this error riight before those: chown: cannot access
> > '/home/mike//qiime_1.9.1/': No such file or directory ...but I added a
> > directory with that name and the error went away..still getting the rest
> > though.
> > 
> > Any ideas? No rush :-)
> > Mike
> > 
> > On Fri, May 6, 2016 at 4:03 PM, Michael G Johnson <
> > mike.johnson@berkeley.edu
> > 
> > > wrote:
> > > 
> > > Nice! Wish we could be there!
> > > 
> > > On Fri, May 6, 2016 at 4:00 PM, alk224 notifications@github.com
> > > wrote:
> > > 
> > > > Will do. Saw Dereks defense this morning, but missed Bo's. Will meet
> > > > him
> > > > at the watering hole instead.
> > > > 
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217583414
> > 
> > > ## 
> > > 
> > > Mike Johnson, MSF
> > > PhD Student, Garbelotto Lab
> > > University of California at Berkeley
> > > Depart of Environmental Science, Policy, and Management
> > 
> > ## 
> > 
> > Mike Johnson, MSF
> > PhD Student, Garbelotto Lab
> > University of California at Berkeley
> > Depart of Environmental Science, Policy, and Management
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217587328
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217587740

## 

Mike Johnson, MSF
PhD Student, Garbelotto Lab
University of California at Berkeley
Depart of Environmental Science, Policy, and Management

**Comment by alk224** [comment]
OK, let's manually see if analyze_primers.py has been corrected. Issue the following command from your home directory:

md5sum akutils-v1.2/akutils_resources/analyze_primers.py

It should return this output:

f3c15b502fccb5d7eb8cf22e32d15090  akutils-v1.2/akutils_resources/analyze_primers.py

Then check where the file needs to go:

md5sum qiime_1.9.1/pprospector-1.0.1-release/lib/python2.7/site-packages/primerprospector/analyze_primers.py

If you get the same result, all is OK (the print_qiime_config at the end will always have a couple of errors). If not, you can manually correct the analyze_primers.py problem with:

sudo cp akutils-v1.2/akutils_resources/analyze_primers.py qiime_1.9.1/pprospector-1.0.1-release/lib/python2.7/site-packages/primerprospector/analyze_primers.py

**Comment by alk224** [comment]
Also, how did you install qiime manually?  Did you use pip? If you used apt-get it will screw things up (files won't be where the installer expects). If you used apt-get, issue the following to remove the apt-get-based installs:

sudo apt-get --purge remove <package>

where <package> is qiime, bamtools or vsearch etc

**Comment by alk224** [comment]
Just a thought, because the packages you initially mentioned are all github repositories, you do have git installed, yes?

And you are using ubuntu 14.04.1, yes?

**Comment by MikeGJohnson** [comment]
1) When I try manually correcting the problem it results in:
cp: cannot create regular file
'qiime_1.9.1/pprospector-1.0.1-release/lib/python2.7/site-packages/primerprospector/analyze_primers.py':
No such file or directory

2) I did use apt-get, so I ran the purge and reran the installer. Go the
same error as above again.

3) I am using ubuntu 16.04 ...is that the problem?

Mike

On Fri, May 6, 2016 at 5:02 PM, alk224 notifications@github.com wrote:

> Just a thought, because the packages you initially mentioned are all
> github repositories, you do have git installed, yes?
> 
> And you are using ubuntu 14.04.1, yes?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/alk224/akutils_ubuntu_installer/issues/1#issuecomment-217590396

## 

Mike Johnson, MSF
PhD Student, Garbelotto Lab
University of California at Berkeley
Depart of Environmental Science, Policy, and Management

**Comment by alk224** [comment]
I tested it on 16.04 when the beta was made available a month or so ago, but it didn't work at all. I think some of the dependencies have changed names in the repositories and I haven't had time to make the necessary updates.

Use the [14.04.1 .iso here](http://old-releases.ubuntu.com/releases/14.04.0/ubuntu-14.04.1-desktop-amd64.iso), reinstall your OS, and try again with the installer.

Follow the [instructions here](http://alk224.github.io/akutils-v1.2/) to get everything in place.

**Comment by alk224** [comment]
closing
